name: Message Producer CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build Message Producer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate With DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=docker.io/vithsutratechnologies/biometric-message-producer:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

  deploy:
    name: Deploy Docker Image to Remote VM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create .env file
        run: |
          echo "SERVER_MODE=${{ secrets.SERVER_MODE }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "MQTT_BROKER_HOST=${{ secrets.MQTT_BROKER_HOST }}" >> .env
          echo "MQTT_BROKER_PORT=${{ secrets.MQTT_BROKER_PORT }}" >> .env
          echo "MQTT_BROKER_USERNAME=${{ secrets.MQTT_BROKER_USERNAME }}" >> .env
          echo "MQTT_BROKER_PASSWORD=${{ secrets.MQTT_BROKER_PASSWORD }}" >> .env
          echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env

      - name: Setup Deploy Environment in Remote VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "${{ secrets.VM_INSTANCE_HOST }}"
          username: "${{ secrets.VM_INSTANCE_USERNAME }}"
          key: "${{ secrets.VM_SSH_PRIVATE_KEY }}"
          script: |
            echo "Connected to VM"
            mkdir -p ~/biometric/biometric-message-producer-deployment

      - name: Copy .env to Remote VM
        run: |
          echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > biometric_ssh_key
          chmod 600 biometric_ssh_key
          scp -o StrictHostKeyChecking=no -i biometric_ssh_key .env ${{ secrets.VM_INSTANCE_USERNAME }}@${{ secrets.VM_INSTANCE_HOST }}:~/biometric/biometric-message-producer-deployment/.env
          rm biometric_ssh_key

      - name: Deploying Docker Image on Remote VM
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "${{ secrets.VM_INSTANCE_HOST }}"
          username: "${{ secrets.VM_INSTANCE_USERNAME }}"
          key: "${{ secrets.VM_SSH_PRIVATE_KEY }}"
          script: |
            IMAGE_NAME=docker.io/vithsutratechnologies/biometric-message-producer:latest
            CONTAINER_NAME=biometric-message-producer
            echo "Pulling latest $IMAGE_NAME image..."
            docker pull $IMAGE_NAME

            echo "Stopping and removing existing $CONTAINER_NAME container if exists..."
            docker ps -q --filter "name=$CONTAINER_NAME" | xargs -r docker stop
            docker ps -aq --filter "name=$CONTAINER_NAME" | xargs -r docker rm

            echo "Pruning unused images and containers..."
            docker container prune -f
            docker image prune -a -f

            echo "Starting new $CONTAINER_NAME container..."
            docker run -d \
              --name $CONTAINER_NAME \
              --env-file $HOME/biometric/biometric-message-producer-deployment/.env
              $IMAGE_NAME

            echo "Deployment completed."